security:

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|uploads|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
